# This file is auto-generated by organjsm tangle. Do not edit directly.
# Source: index.org

# [[file:index.org::232]]
"""Tests for the agent_rex library."""

import asyncio
from typing import TypeVar, AsyncIterable, List
import pytest

T = TypeVar('T')

from agent_rex import (
  # Creation
  just, of, from_promise, from_iter, periodic, empty, never,
  iterate, unfold, start_with, concat,
  # Composition
  pipe,
  # Transformation
  map, constant, scan, tap, await_tap, continue_with,
  concat_all, concat_map,
  # Filtering
  filter, skip_repeats, skip_repeats_with,
  # Slicing
  take, skip, slice, take_while, skip_while, take_until,
  # Time
  delay,
  # Error handling
  recover_with, throw_error, retry, RetryOptions,
  # Concurrent
  merge, merge_all, chain, flat_map, switch_map, latest,
  # Buffering
  buffer, eager,
  # Multicasting
  ReplaySubject, replay, share,
  # Types
  UnfoldResult
)
# unnamed ends here

# [[file:index.org::564]]
class TestJust:
  async def test_emits_single_value(self):
    result = await collect(just(42))
    assert result == [42]
  async def test_of_is_alias(self):
    result = await collect(of("hello"))
    assert result == ["hello"]
# unnamed ends here

# [[file:index.org::987]]
class TestFromPromise:
  async def test_emits_awaitable_result(self):
    async def get_value():
      return 99
    
    result = await collect(from_promise(get_value()))
    assert result == [99]
# unnamed ends here

# [[file:index.org::1309]]
class TestFromIter:
  async def test_from_list(self):
    result = await collect(from_iter([1, 2, 3]))
    assert result == [1, 2, 3]
  async def test_from_tuple(self):
    result = await collect(from_iter((4, 5, 6)))
    assert result == [4, 5, 6]
  async def test_from_async_iterable(self):
    async def gen():
      for i in [7, 8, 9]:
        yield i
    result = await collect(from_iter(gen()))
    assert result == [7, 8, 9]
# unnamed ends here

# [[file:index.org::1665]]
class TestPeriodic:
  async def test_emits_none_periodically(self):
    result = await collect(pipe(
      periodic(0.01),
      take(3)
    ))
    assert result == [None, None, None]
# unnamed ends here

# [[file:index.org::1949]]
class TestEmpty:
  async def test_completes_immediately(self):
    result = await collect(empty())
    assert result == []
# unnamed ends here

# [[file:index.org::2169]]

# unnamed ends here

# [[file:index.org::2453]]
class TestIterate:
  async def test_generates_sequence(self):
    result = await collect(pipe(
      iterate(1, lambda x: x * 2),
      take(5)
    ))
    assert result == [1, 2, 4, 8, 16]
# unnamed ends here

# [[file:index.org::2803]]
class TestUnfold:
  async def test_unfolds_until_done(self):
    result = await collect(unfold(
      1,
      lambda x: UnfoldResult(
        value=x,
        next_seed=x + 1,
        done=x > 3
      )
    ))
    assert result == [1, 2, 3]
# unnamed ends here

# [[file:index.org::3236]]
class TestStartWith:
  async def test_prepends_value(self):
    result = await collect(start_with(0, from_iter([1, 2, 3])))
    assert result == [0, 1, 2, 3]
# unnamed ends here

# [[file:index.org::3511]]
class TestConcat:
  async def test_concatenates_streams(self):
    result = await collect(concat(
      from_iter([1, 2]),
      from_iter([3, 4]),
      from_iter([5])
    ))
    assert result == [1, 2, 3, 4, 5]
# unnamed ends here

# [[file:index.org::3995]]

# unnamed ends here

# [[file:index.org::4230]]
class TestPipe:
  async def test_composes_operators(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]),
      filter(lambda x: x % 2 == 0),
      map(lambda x: x * 10),
      take(3),
    ))
    assert result == [20, 40, 60]

  async def test_complex_pipeline(self):
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      concat_map(lambda x: from_iter([x, -x])),
      filter(lambda x: x > 0),
      scan(lambda acc, x: acc + x, 0),
    ))
    assert result == [0, 1, 3, 6]
# unnamed ends here

# [[file:index.org::4415]]
class TestMap:
  async def test_transforms_values(self):
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      map(lambda x: x * 10)
    ))
    assert result == [10, 20, 30]

  async def test_async_transform(self):
    async def async_transform(x):
      await asyncio.sleep(0)
      return x * 2
    
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      map(async_transform)
    ))
    assert result == [2, 4, 6]
# unnamed ends here

# [[file:index.org::4794]]
class TestConstant:
  async def test_replaces_with_constant(self):
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      constant("x")
    ))
    assert result == ["x", "x", "x"]
# unnamed ends here

# [[file:index.org::5137]]
class TestScan:
  async def test_accumulates_values(self):
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      scan(lambda acc, x: acc + x, 0)
    ))
    assert result == [0, 1, 3, 6]
# unnamed ends here

# [[file:index.org::5570]]
class TestTap:
  async def test_performs_side_effect(self):
    side_effects = []
    
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      tap(lambda x: side_effects.append(x))
    ))
    
    assert result == [1, 2, 3]
    assert side_effects == [1, 2, 3]
# unnamed ends here

# [[file:index.org::5901]]

# unnamed ends here

# [[file:index.org::6238]]
class TestContinueWith:
  async def test_continues_with_stream(self):
    result = await collect(pipe(
      from_iter([1, 2]),
      continue_with(lambda: from_iter([3, 4]))
    ))
    assert result == [1, 2, 3, 4]
# unnamed ends here

# [[file:index.org::6596]]
class TestConcatAll:
  async def test_flattens_stream_of_streams(self):
    async def stream_of_streams():
      yield from_iter([1, 2])
      yield from_iter([3, 4])
    
    result = await collect(concat_all(stream_of_streams()))
    assert result == [1, 2, 3, 4]
# unnamed ends here

# [[file:index.org::6926]]
class TestConcatMap:
  async def test_maps_and_concatenates(self):
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      concat_map(lambda x: from_iter([x, x * 10]))
    ))
    assert result == [1, 10, 2, 20, 3, 30]
# unnamed ends here

# [[file:index.org::7264]]
class TestFilter:
  async def test_filters_values(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 5]),
      filter(lambda x: x % 2 == 0)
    ))
    assert result == [2, 4]

  async def test_async_predicate(self):
    async def is_even(x):
      await asyncio.sleep(0)
      return x % 2 == 0
    
    result = await collect(pipe(
      from_iter([1, 2, 3, 4]),
      filter(is_even)
    ))
    assert result == [2, 4]
# unnamed ends here

# [[file:index.org::7700]]
class TestSkipRepeats:
  async def test_removes_consecutive_duplicates(self):
    result = await collect(skip_repeats(from_iter([1, 1, 2, 2, 3, 1, 1])))
    assert result == [1, 2, 3, 1]
# unnamed ends here

# [[file:index.org::7841]]
class TestSkipRepeatsWith:
  async def test_custom_equality(self):
    result = await collect(pipe(
      from_iter(["A", "a", "B", "b"]),
      skip_repeats_with(lambda a, b: a.lower() == b.lower())
    ))
    assert result == ["A", "B"]
# unnamed ends here

# [[file:index.org::8303]]
class TestTake:
  async def test_takes_n_values(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 5]),
      take(3)
    ))
    assert result == [1, 2, 3]
# unnamed ends here

# [[file:index.org::8652]]
class TestSkip:
  async def test_skips_n_values(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 5]),
      skip(2)
    ))
    assert result == [3, 4, 5]
# unnamed ends here

# [[file:index.org::9027]]
class TestSlice:
  async def test_extracts_slice(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 5]),
      slice(1, 4)
    ))
    assert result == [2, 3, 4]
# unnamed ends here

# [[file:index.org::9420]]
class TestTakeWhile:
  async def test_takes_while_true(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 1]),
      take_while(lambda x: x < 4)
    ))
    assert result == [1, 2, 3]
# unnamed ends here

# [[file:index.org::9815]]
class TestSkipWhile:
  async def test_skips_while_true(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 1]),
      skip_while(lambda x: x < 3)
    ))
    assert result == [3, 4, 1]
# unnamed ends here

# [[file:index.org::10210]]
class TestTakeUntil:
  async def test_takes_until(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 5]),
      take_until(lambda x: x == 3)
    ))
    assert result == [1, 2]
# unnamed ends here

# [[file:index.org::10591]]
class TestDelay:
  async def test_delays_values(self):
    result = await collect(pipe(
      from_iter([1, 2, 3]),
      delay(0.01)
    ))
    assert result == [1, 2, 3]
# unnamed ends here

# [[file:index.org::11057]]

# unnamed ends here

# [[file:index.org::11684]]

# unnamed ends here

# [[file:index.org::12321]]
class TestRecoverWith:
  async def test_recovers_from_error(self):
    async def failing_stream():
      yield 1
      raise ValueError("oops")
    
    result = await collect(pipe(
      failing_stream(),
      recover_with(lambda e: from_iter([99]))
    ))
    assert result == [1, 99]
# unnamed ends here

# [[file:index.org::12718]]

# unnamed ends here

# [[file:index.org::12925]]
class TestThrowError:
  async def test_throws_error(self):
    with pytest.raises(ValueError, match="oops"):
      await collect(throw_error(ValueError("oops")))
# unnamed ends here

# [[file:index.org::13307]]
class TestRetry:
  async def test_retries_until_success(self):
    attempt = 0
    
    def create_stream():
      nonlocal attempt
      attempt += 1
      async def stream():
        if attempt < 3:
          yield attempt
          raise ValueError(f"fail {attempt}")
        else:
          yield attempt
      return stream()
    
    result = await collect(retry(3, create_stream))
    assert result == [1, 2, 3]
# unnamed ends here

# [[file:index.org::14104]]
class TestMerge:
  async def test_merges_streams(self):
    async def slow_stream():
      yield 1
      await asyncio.sleep(0.02)
      yield 3
    
    async def fast_stream():
      await asyncio.sleep(0.01)
      yield 2
    
    result = await collect(merge(slow_stream(), fast_stream()))
    assert sorted(result) == [1, 2, 3]
# unnamed ends here

# [[file:index.org::14544]]
class TestMergeAll:
  async def test_merges_stream_of_streams(self):
    async def stream_of_streams():
      yield from_iter([1, 2])
      yield from_iter([3, 4])
    
    result = await collect(merge_all(stream_of_streams()))
    assert sorted(result) == [1, 2, 3, 4]
# unnamed ends here

# [[file:index.org::14876]]
class TestChain:
  async def test_maps_and_merges(self):
    result = await collect(pipe(
      from_iter([1, 2]),
      chain(lambda x: from_iter([x, x * 10]))
    ))
    assert sorted(result) == [1, 2, 10, 20]
# unnamed ends here

# [[file:index.org::15417]]

# unnamed ends here

# [[file:index.org::15855]]
class TestLatest:
  async def test_combines_latest(self):
    async def stream_a():
      yield 1
      await asyncio.sleep(0.02)
      yield 2
    
    async def stream_b():
      await asyncio.sleep(0.01)
      yield "a"
      await asyncio.sleep(0.02)
      yield "b"
    
    result = await collect(latest(stream_a(), stream_b()))
    # After first emit from both: (1, "a")
    # After 2 from a: (2, "a") 
    # After "b" from b: (2, "b")
    assert len(result) >= 1
# unnamed ends here

# [[file:index.org::16226]]

# unnamed ends here

# [[file:index.org::16554]]

# unnamed ends here

# [[file:index.org::16922]]

# unnamed ends here

# [[file:index.org::17272]]
class TestBuffer:
  async def test_buffers_values(self):
    result = await collect(pipe(
      from_iter([1, 2, 3, 4, 5]),
      buffer(2)
    ))
    assert result == [[1, 2], [3, 4], [5]]
# unnamed ends here

# [[file:index.org::17700]]

# unnamed ends here

# [[file:index.org::18154]]

# unnamed ends here

# [[file:index.org::18645]]
class TestEager:
  async def test_prefetches_values(self):
    events = []
    
    async def slow_producer():
      for i in range(3):
        events.append(f"produce_{i}")
        yield i
    
    stream = pipe(
      slow_producer(),
      eager(10)
    )
    
    events.append("created")
    result = await collect(stream)
    assert result == [0, 1, 2]
# unnamed ends here

# [[file:index.org::19211]]
class TestReplaySubject:
  async def test_replays_to_new_subscribers(self):
    subject = ReplaySubject[int](buffer_size=10)
    subject.next(1)
    subject.next(2)
    
    result = await collect_n(2, subject)
    assert result == [1, 2]

  async def test_buffers_limited(self):
    subject = ReplaySubject[int](buffer_size=2)
    subject.next(1)
    subject.next(2)
    subject.next(3)
    
    assert subject.get_buffer() == [2, 3]
# unnamed ends here

# [[file:index.org::19590]]
class TestReplay:
  async def test_replays_buffered(self):
    source = from_iter([1, 2, 3])
    replayed = replay(10, source)
    
    result1 = await collect(replayed)
    # Second subscriber would get replayed values
    assert result1 == [1, 2, 3]
# unnamed ends here

# [[file:index.org::20091]]
class TestShare:
  async def test_shares_without_buffer(self):
    source = from_iter([1, 2, 3])
    shared = share(source)
    
    result = await collect(shared)
    assert result == [1, 2, 3]
# unnamed ends here

# [[file:index.org::20491]]

# unnamed ends here

# [[file:index.org::20863]]

# unnamed ends here

# [[file:index.org::23267]]
async def collect(stream: AsyncIterable[T]) -> List[T]:
  """Collect all values from a stream into a list."""
  return [value async for value in stream]
# unnamed ends here

# [[file:index.org::23284]]
async def collect_n(n: int, stream: AsyncIterable[T]) -> List[T]:
  """Collect exactly N values from a stream."""
  values: List[T] = []
  async for value in stream:
    values.append(value)
    if len(values) >= n:
      break
  return values
# unnamed ends here

# [[file:index.org::23306]]
async def drain(stream: AsyncIterable[T]) -> None:
  """Consume all values from a stream, discarding them."""
  async for _ in stream:
    pass
# unnamed ends here
